[2023-10-02T07:32:31.755+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: H8_Automation_Clean.connect_es manual__2023-10-02T07:32:27.025618+00:00 [queued]>
[2023-10-02T07:32:31.768+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: H8_Automation_Clean.connect_es manual__2023-10-02T07:32:27.025618+00:00 [queued]>
[2023-10-02T07:32:31.769+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-10-02T07:32:31.770+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2023-10-02T07:32:31.771+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-10-02T07:32:31.788+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): connect_es> on 2023-10-02 07:32:27.025618+00:00
[2023-10-02T07:32:31.796+0000] {standard_task_runner.py:52} INFO - Started process 968 to run task
[2023-10-02T07:32:31.800+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'H8_Automation_Clean', 'connect_es', 'manual__2023-10-02T07:32:27.025618+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_rais_yufli.py', '--cfg-path', '/tmp/tmpanhydhxa', '--error-file', '/tmp/tmpi_r26rga']
[2023-10-02T07:32:31.803+0000] {standard_task_runner.py:80} INFO - Job 34: Subtask connect_es
[2023-10-02T07:32:31.891+0000] {task_command.py:371} INFO - Running <TaskInstance: H8_Automation_Clean.connect_es manual__2023-10-02T07:32:27.025618+00:00 [running]> on host 5f5d0b98abe4
[2023-10-02T07:32:31.984+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Rais
AIRFLOW_CTX_DAG_ID=H8_Automation_Clean
AIRFLOW_CTX_TASK_ID=connect_es
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T07:32:27.025618+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-02T07:32:27.025618+00:00
[2023-10-02T07:32:32.054+0000] {base.py:299} WARNING - PUT http://elasticsearch:9200/table_M3/_doc/1 [status:400 request:0.055s]
[2023-10-02T07:32:32.056+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/connect_es.py", line 13, in connect_es
    res = es.index(index="table_M3", id=i+1, body=doc)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 411, in index
    body=body,
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/transport.py", line 388, in perform_request
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 331, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'invalid_index_name_exception', 'Invalid index name [table_M3], must be lowercase')
[2023-10-02T07:32:32.081+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=H8_Automation_Clean, task_id=connect_es, execution_date=20231002T073227, start_date=20231002T073231, end_date=20231002T073232
[2023-10-02T07:32:32.098+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 34 for task connect_es (RequestError(400, 'invalid_index_name_exception', 'Invalid index name [table_M3], must be lowercase'); 968)
[2023-10-02T07:32:32.138+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-02T07:32:32.180+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
